language: go

go:
  - 1.7
  - master
  
script: 
  - ./build.sh


install:
  - go get github.com/revel/revel
  - go get github.com/revel/cmd/revel
  - go get github.com/go-xorm/xorm
  - go get gopkg.in/redis.v5
  - go get github.com/go-sql-driver/mysql
